// Package enrollclient performs the device half of enrolment.
//
// It lives apart from the CLI so that the tests, the CLI and eventually meshpd all
// drive the same code. A test client that merely resembles the real one proves that
// the resemblance is accurate and nothing else.
package enrollclient

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/netip"
	"time"

	"github.com/google/uuid"

	"github.com/meshpnet/meshp/internal/controlurl"
	"github.com/meshpnet/meshp/internal/keys"
)

// Client talks to a control plane's enrolment endpoints.
type Client struct {
	baseURL string
	urlErr  error
	http    *http.Client
}

// New returns a client for a control plane at baseURL.
//
// An unusable URL is kept and reported when it is used rather than at construction, so a
// caller that builds a client early still gets one error at the point it matters.
func New(baseURL string, httpClient *http.Client) *Client {
	if httpClient == nil {
		httpClient = &http.Client{Timeout: 30 * time.Second}
	}
	c := &Client{http: httpClient}
	validated, err := controlurl.Validate(baseURL)
	if err != nil {
		c.urlErr = err
		return c
	}
	c.baseURL = validated
	return c
}

// APIError is a refusal the control plane explained.
type APIError struct {
	Status  int
	Code    string
	Message string
}

func (e *APIError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("%s (%s)", e.Message, e.Code)
	}
	return fmt.Sprintf("control plane returned %d", e.Status)
}

// JoinRequest is everything needed to enrol.
//
// The keys are generated by the caller and only their public halves are sent. This
// package has no way to transmit a private key and no reason to hold one
// (Invariant 1).
type JoinRequest struct {
	Token     string
	Identity  keys.Identity
	WireGuard keys.WireGuardPair

	Name         string
	Hostname     string
	OS           string
	OSVersion    string
	AgentVersion string
}

// JoinResult is what the control plane assigned.
type JoinResult struct {
	DeviceID      uuid.UUID   `json:"device_id"`
	MembershipID  uuid.UUID   `json:"membership_id"`
	NetworkID     uuid.UUID   `json:"network_id"`
	InterfaceName string      `json:"interface_name"`
	AddressV4     *netip.Addr `json:"address_v4"`
	AddressV6     *netip.Addr `json:"address_v6"`
	StateVersion  int64       `json:"state_version"`
}

// Join runs the two-step exchange: ask for a challenge, sign it, redeem.
func (c *Client) Join(ctx context.Context, req JoinRequest) (JoinResult, error) {
	challenge, err := c.challenge(ctx, req.Token, req.Identity)
	if err != nil {
		return JoinResult{}, err
	}

	// Signed over exactly the bytes the server issued. Re-encoding or normalising
	// them here would produce a signature over something else.
	signature := req.Identity.Sign(challenge)

	body := map[string]string{
		"token":                req.Token,
		"identity_public_key":  base64.StdEncoding.EncodeToString(req.Identity.Public),
		"challenge":            base64.StdEncoding.EncodeToString(challenge),
		"signature":            base64.StdEncoding.EncodeToString(signature),
		"wireguard_public_key": req.WireGuard.Public.String(),
	}
	for k, v := range map[string]string{
		"name": req.Name, "hostname": req.Hostname, "os": req.OS,
		"os_version": req.OSVersion, "agent_version": req.AgentVersion,
	} {
		if v != "" {
			body[k] = v
		}
	}

	var out JoinResult
	if err := c.post(ctx, "/api/v1/enroll", body, &out); err != nil {
		return JoinResult{}, err
	}
	return out, nil
}

// challenge asks for bytes to sign.
func (c *Client) challenge(ctx context.Context, token string, identity keys.Identity) ([]byte, error) {
	var out struct {
		Challenge string    `json:"challenge"`
		ExpiresAt time.Time `json:"expires_at"`
	}
	err := c.post(ctx, "/api/v1/enroll/challenge", map[string]string{
		"token":               token,
		"identity_public_key": base64.StdEncoding.EncodeToString(identity.Public),
	}, &out)
	if err != nil {
		return nil, err
	}
	raw, err := base64.StdEncoding.DecodeString(out.Challenge)
	if err != nil {
		return nil, fmt.Errorf("enrollclient: challenge is not valid base64: %w", err)
	}
	return raw, nil
}

func (c *Client) post(ctx context.Context, path string, body, out any) error {
	if c.urlErr != nil {
		return c.urlErr
	}
	encoded, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("enrollclient: encoding request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+path, bytes.NewReader(encoded))
	if err != nil {
		return fmt.Errorf("enrollclient: building request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("enrollclient: reaching %s: %w", c.baseURL, err)
	}
	defer func() {
		_, _ = io.Copy(io.Discard, resp.Body)
		_ = resp.Body.Close()
	}()

	// Bounded, because the other end is not necessarily the control plane — it might
	// be a captive portal or a proxy with a great deal to say.
	payload, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return fmt.Errorf("enrollclient: reading response: %w", err)
	}

	if resp.StatusCode >= 400 {
		apiErr := &APIError{Status: resp.StatusCode}
		var parsed struct {
			Error   string `json:"error"`
			Message string `json:"message"`
		}
		if json.Unmarshal(payload, &parsed) == nil {
			apiErr.Code = parsed.Error
			apiErr.Message = parsed.Message
		}
		return apiErr
	}

	if out != nil {
		if err := json.Unmarshal(payload, out); err != nil {
			return fmt.Errorf("enrollclient: decoding response: %w", err)
		}
	}
	return nil
}
