#!/usr/bin/env bash
#
# Enrolment and the control channel, end to end, with the real binaries:
#
#   meshpd comes up with no state at all and is still usable
#   a token is minted over the administrative API
#   `meshp join` asks the daemon, which is what generates the keys
#   the keys land with restrictive permissions, written by the daemon
#   `meshp status` reports a live session, and says the tunnel is not up
#   the same token is refused a second time
#   the agent converges: applied version catches up with the network's
#   the session is cleared when the agent exits
#   no private key material appears where it should not
#
# Usage: e2e-enrol.sh <postgres-url>
#
# The unit tests cover each of these against a library. This covers what a person
# actually runs, which is where the wiring mistakes are — flag parsing, file modes,
# socket permissions, exit codes.
set -euo pipefail

DB_URL="${1:?usage: e2e-enrol.sh <postgres-url>}"
PORT="${MESHP_E2E_PORT:-8099}"
BASE="http://127.0.0.1:${PORT}"
ADMIN_TOKEN="e2e-administrative-token-not-a-secret"
SECRET_KEY="e2e-deployment-secret-not-a-secret"

# Short paths on purpose: a unix socket path has a hard limit near 100 bytes, and mktemp
# under a long temporary root can exceed it — which fails with "invalid argument" and no
# hint about why.
WORK="$(mktemp -d /tmp/mpe2e.XXXXXX)"
CONTROL_LOG="$WORK/control.log"
AGENT_LOG="$WORK/meshpd.log"
RELAY_LOG="$WORK/relay.log"
STATE_DIR="$WORK/state"
SOCKET="$WORK/d.sock"
CONTROL_PID=""
AGENT_PID=""
RELAY_PID=""

# A relay of this deployment's own, on a loopback port. Every peer is relayed until
# discovery exists (ADR-0002), so without one the agent's peers are configured and
# unreachable — and the assertions below would pass on a mesh that carries nothing.
RELAY_PORT="${MESHP_E2E_RELAY_PORT:-3479}"
RELAY_ID="e2e"

cleanup() {
  [ -n "$AGENT_PID" ] && kill "$AGENT_PID" 2>/dev/null || true
  [ -n "$RELAY_PID" ] && kill "$RELAY_PID" 2>/dev/null || true
  [ -n "$CONTROL_PID" ] && kill "$CONTROL_PID" 2>/dev/null || true
  # Never leave an egress lock behind on a host that ran this, however the run ended. The
  # table this creates is empty and harmless, but leaving one named meshp_lock would make
  # the next run's reclamation assertion pass before the daemon had done anything.
  command -v nft >/dev/null 2>&1 && nft delete table inet meshp_lock 2>/dev/null || true
  rm -rf "$WORK"
}
trap cleanup EXIT

fail() {
  echo "FAIL: $*" >&2
  echo "--- control plane log ---" >&2; cat "$CONTROL_LOG" >&2 2>/dev/null || true
  echo "--- relay log ---" >&2; cat "$RELAY_LOG" >&2 2>/dev/null || true
  echo "--- agent log ---" >&2; cat "$AGENT_LOG" >&2 2>/dev/null || true
  exit 1
}

mode_of() { stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"; }

for binary in ./bin/meshp ./bin/meshpd ./bin/meshp-control ./bin/meshp-relay; do
  [ -x "$binary" ] || fail "$binary is missing; run make build"
done

# One keypair: the control plane signs relay tokens with the private half and the relay
# verifies them with the public half. Generated by the same command an operator runs, so a
# change to its output format fails here rather than in someone's deployment.
./bin/meshp-control --generate-relay-key >"$WORK/relay.env" \
  || fail "could not generate a relay keypair"
RELAY_SIGNING_KEY="$(sed -n 's/^MESHP_RELAY_SIGNING_KEY=//p' "$WORK/relay.env")"
RELAY_ISSUER_KEY="$(sed -n 's/^MESHP_RELAY_ISSUER_KEY=//p' "$WORK/relay.env")"
[ -n "$RELAY_SIGNING_KEY" ] && [ -n "$RELAY_ISSUER_KEY" ] \
  || { cat "$WORK/relay.env" >&2; fail "the relay keygen output did not contain both keys"; }

echo "starting meshp-relay on 127.0.0.1:${RELAY_PORT}"
MESHP_RELAY_LISTEN="127.0.0.1:${RELAY_PORT}" \
MESHP_RELAY_ISSUER_KEY="$RELAY_ISSUER_KEY" \
MESHP_RELAY_ADMIN_ADDR="127.0.0.1:9099" \
  ./bin/meshp-relay >"$RELAY_LOG" 2>&1 &
RELAY_PID=$!

# A certificate for this control plane, so the whole run goes over TLS with the agent
# verifying it. Plaintext to anything but loopback is refused by the agent now, and a test
# that ran over http would be exercising the one path a real deployment must never take.
TLS_DIR="$WORK/tls"
mkdir -p "$TLS_DIR"
if command -v openssl >/dev/null 2>&1; then
  openssl req -x509 -newkey rsa:2048 -nodes -days 1 \
    -keyout "$TLS_DIR/key.pem" -out "$TLS_DIR/cert.pem" \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1 \
    || fail "could not generate a test certificate"
  BASE="https://localhost:${PORT}"
  # The agent and curl both verify it. Trusting this one certificate rather than disabling
  # verification, because "does the agent verify" is exactly what is under test.
  export SSL_CERT_FILE="$TLS_DIR/cert.pem"
  CURL_CA=(--cacert "$TLS_DIR/cert.pem")
  echo "serving the control plane over TLS"
else
  CURL_CA=()
  echo "openssl is unavailable; running without TLS"
fi

echo "starting meshp-control on ${BASE}"
MESHP_DATABASE_URL="$DB_URL" \
MESHP_LISTEN_ADDR="127.0.0.1:${PORT}" \
MESHP_SECRET_KEY="$SECRET_KEY" \
MESHP_ADMIN_TOKEN="$ADMIN_TOKEN" \
MESHP_RELAY_SIGNING_KEY="$RELAY_SIGNING_KEY" \
MESHP_RELAYS="${RELAY_ID}=127.0.0.1:${RELAY_PORT}" \
MESHP_TLS_CERT="${TLS_DIR}/cert.pem" \
MESHP_TLS_KEY="${TLS_DIR}/key.pem" \
  ./bin/meshp-control >"$CONTROL_LOG" 2>&1 &
CONTROL_PID=$!

for _ in $(seq 1 30); do
  curl -fsS "${CURL_CA[@]}" "${BASE}/readyz" >/dev/null 2>&1 && break
  sleep 1
done
curl -fsS "${CURL_CA[@]}" "${BASE}/readyz" >/dev/null 2>&1 || fail "control plane never became ready"

# A fail-closed lock left behind by a previous life, so that starting the daemon has
# something to reclaim (ADR-0011). This is the only thing standing between a `kill -9` and a
# machine somebody has to physically recover, so it is asserted against the real binary
# rather than only in a unit test.
#
# The table is created empty, with no chain and no policy. What is under test is whether
# meshpd finds and removes a table it owns, and an empty one exercises exactly that — while
# a real locking chain here would be installed in this host's root namespace and would take
# the CI runner's own network away, including the connection this job is reporting over. The
# rules themselves are proved against a real kernel in internal/nftables, inside a namespace.
reclaimable=0
if command -v nft >/dev/null 2>&1 && nft add table inet meshp_lock 2>/dev/null; then
  reclaimable=1
  echo "left a stale egress lock behind for the daemon to find"
fi

echo "starting meshpd with no state at all"
# Deliberately before enrolment. An agent that gives up when it has nothing to do cannot
# be joined without restarting a service, which is a paper cut people script around.
./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR" --socket "$SOCKET" --log-level debug >"$AGENT_LOG" 2>&1 &
AGENT_PID=$!

for _ in $(seq 1 30); do
  [ -S "$SOCKET" ] && ./bin/meshp status --socket "$SOCKET" >/dev/null 2>&1 && break
  sleep 1
done
./bin/meshp status --socket "$SOCKET" >"$WORK/status-before.out" 2>&1 \
  || fail "the daemon never answered on its socket"
grep -q 'not enrolled' "$WORK/status-before.out" \
  || fail "an unenrolled daemon did not say so: $(cat "$WORK/status-before.out")"
echo "  socket answers: $(head -1 "$WORK/status-before.out")"

# The resolver is listening, on a daemon that has joined nothing.
#
# Asserted here because nothing else can. The daemon constructs a resolver and starts it in
# a goroutine, and deleting that goroutine compiles cleanly and passes every unit test in
# the tree — the package would be built, wired, and never listening, which is the exact
# shape ADR-0018 is about and the shape WithChooser was missing in for two releases.
#
# Before enrolment on purpose: the resolver comes up ahead of any membership, so a device
# with no names still answers, and a device whose names are missing later is a different
# problem from one whose resolver never bound.
grep -q '  resolver  127\.' "$WORK/status-before.out" \
  || fail "the daemon is not answering names: $(grep resolver "$WORK/status-before.out" || echo 'no resolver line at all')"
echo "  resolver: $(grep '  resolver' "$WORK/status-before.out" | sed 's/^ *//')"

# And the stale lock is gone. Asserted on a daemon that is not enrolled, which is the case
# that matters most: a device whose membership was revoked, or whose state was wiped, still
# has to get its network back. Nothing in desired state can rescue it, because it has none.
if [ "$reclaimable" = "1" ]; then
  if nft list table inet meshp_lock >/dev/null 2>&1; then
    echo "--- agent log ---" >&2; head -20 "$AGENT_LOG" >&2
    nft delete table inet meshp_lock 2>/dev/null || true
    fail "the daemon started and left a previous run's egress lock in place"
  fi
  # And said so, because a machine that had no egress and then did needs one line in the log
  # explaining it. Removing it silently is how the next person spends a day on it.
  grep -q 'fail-closed lock from a previous run' "$AGENT_LOG" \
    || { head -20 "$AGENT_LOG" >&2; fail "the lock was removed without a word about it"; }
  echo "  the daemon reclaimed it and said so"

  # And it happens before the state file is read, which is the whole of why the ordering in
  # run() is what it is. Reading state can fail — a truncated write, a disk that filled, a
  # file somebody edited — and that failure exits the daemon. A device whose egress is being
  # refused would then stay that way for as long as its state file stayed broken: a machine
  # bricked by malformed JSON.
  nft add table inet meshp_lock 2>/dev/null || true
  BROKEN="$WORK/broken"
  mkdir -p "$BROKEN"
  printf 'this is not json' >"$BROKEN/state.json"
  ./bin/meshpd --state-dir "$BROKEN" --socket "$WORK/broken.sock" \
    >"$WORK/broken.log" 2>&1 || true
  if nft list table inet meshp_lock >/dev/null 2>&1; then
    echo "--- daemon log ---" >&2; cat "$WORK/broken.log" >&2
    nft delete table inet meshp_lock 2>/dev/null || true
    fail "a daemon that could not read its state left the egress lock in place"
  fi
  echo "  and reclaims it even when the state file is unreadable"
fi

echo "the socket is owner-only"
# A privilege boundary: anything that can reach this socket can enrol the device and,
# once tunnels exist, decide where its traffic goes.
socket_mode="$(mode_of "$SOCKET")"
[ "$socket_mode" = "600" ] || fail "the socket is ${socket_mode}, want 600"
echo "  0${socket_mode}"

echo "seeding a network with address pools"
# A distinct slug and address pool per run. Seeding fixed names made this script pass exactly
# once against any given database and fail on every rerun, which CI never noticed because it
# gets a fresh Postgres each time. A test that only works on a virgin database is one nobody
# can reproduce locally.
RUN_ID="$$"
SLUG="e2e-${RUN_ID}"
# The third octet keeps concurrent and repeated runs out of each other's pools.
OCTET="$(( RUN_ID % 250 + 1 ))"
# Explicit casts: inside a UNION the literals have no inferable type, and cidr will not
# accept text.
NETWORK_ID="$(psql "$DB_URL" -tAqc "
  WITH o AS (INSERT INTO organizations (slug, name) VALUES ('${SLUG}', 'End To End ${RUN_ID}') RETURNING id),
       n AS (INSERT INTO networks (organization_id, slug, name) SELECT id, '${SLUG}', 'End To End ${RUN_ID}' FROM o RETURNING id),
       p AS (INSERT INTO address_pools (network_id, prefix, family, purpose)
             SELECT id, '100.90.${OCTET}.0/24'::cidr, 4, 'device' FROM n
             UNION ALL
             SELECT id, ('fd7c:6d65:7368:' || to_hex(${OCTET}) || '::/120')::cidr, 6, 'device' FROM n
             RETURNING network_id)
  SELECT DISTINCT network_id FROM p")"
[ -n "$NETWORK_ID" ] || fail "could not seed a network"
echo "  network ${NETWORK_ID}"

echo "minting an enrolment token"
MINT="$(curl -fsS "${CURL_CA[@]}" -X POST \
  -H "Authorization: Bearer ${ADMIN_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{"max_uses":1,"expires_in_seconds":600,"tags":["e2e"]}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens")"
TOKEN="$(printf '%s' "$MINT" | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')"
[ -n "$TOKEN" ] || fail "no token in the mint response: $MINT"
case "$TOKEN" in
  meshp_tok_*) ;;
  *) fail "token does not carry the expected prefix: $TOKEN" ;;
esac
echo "  minted ${TOKEN:0:18}…"

echo "the administrative API refuses an unauthenticated caller"
status="$(curl -s "${CURL_CA[@]}" -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' -d '{}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens")"
[ "$status" = "401" ] || fail "minting without a token returned ${status}, want 401"

echo "meshp join"
./bin/meshp join "$TOKEN" --control-url "$BASE" --socket "$SOCKET" --name e2e-device \
  >"$WORK/join.out" 2>&1 || fail "join failed: $(cat "$WORK/join.out")"
sed 's/^/  /' "$WORK/join.out"
grep -q 'enrolled in network' "$WORK/join.out" || fail "join did not report success"
grep -qE "address     100\.90\.${OCTET}\." "$WORK/join.out" || fail "join reported no IPv4 address"

echo "the keys were written by the daemon, and only it can read them"
[ -f "$STATE_DIR/state.json" ] || fail "no state file was written"
file_mode="$(mode_of "$STATE_DIR/state.json")"
dir_mode="$(mode_of "$STATE_DIR")"
[ "$file_mode" = "600" ] || fail "state file is ${file_mode}, want 600"
[ "$dir_mode" = "700" ] || fail "state directory is ${dir_mode}, want 700"
echo "  file 0${file_mode}, directory 0${dir_mode}"

echo "no private key crossed the socket or reached a log"
# Invariant 1. The CLI asked the daemon to enrol; it must not have been handed anything
# secret in return, and the control plane must never have seen one.
if grep -qiE 'private' "$WORK/join.out"; then fail "the CLI's output mentions a private key"; fi
priv="$(sed -n 's/.*"wireguard_private_key": *"\([^"]*\)".*/\1/p' "$STATE_DIR/state.json" | head -1)"
[ -n "$priv" ] || fail "could not read the stored private key to check for leaks"
if grep -qF "$priv" "$WORK/join.out"; then fail "the CLI printed the WireGuard private key"; fi
if grep -qF "$priv" "$CONTROL_LOG"; then fail "the control plane logged the WireGuard private key"; fi

# Whether a tunnel is possible here at all, decided once and reused. Deciding it rather than
# assuming it is why this section survives both a laptop and a privileged Linux runner.
tunnel_possible=0
if [ "$(uname -s)" = "Linux" ] && [ "$(id -u)" = "0" ] && ip link add dev wgprobe0 type wireguard 2>/dev/null; then
  ip link del dev wgprobe0
  tunnel_possible=1
fi

# And whether this host has a resolver meshp knows how to configure and put back. Decided by
# asking resolved to speak rather than by looking for the binary: a container can have
# resolvectl installed with no daemon behind it, and the agent makes the same call for the
# same reason (internal/resolved.New).
resolved_possible=0
if [ "$tunnel_possible" = "1" ] && command -v resolvectl >/dev/null 2>&1 && resolvectl status >/dev/null 2>&1; then
  resolved_possible=1
fi

# Over TLS, and the control plane says so. A run that quietly fell back to plaintext would
# pass every assertion below while testing the one path a real deployment must never take.
if [ -n "${CURL_CA[*]}" ]; then
  grep -q 'msg=listening.*tls=true' "$CONTROL_LOG" \
    || { grep -i listening "$CONTROL_LOG" >&2; fail "the control plane is not serving TLS"; }
  grep -q 'control     https://' "$WORK/status.out" 2>/dev/null \
    || ./bin/meshp status --socket "$SOCKET" | grep -q 'control     https://' \
    || fail "the agent is not talking to the control plane over TLS"
  echo "  the session runs over TLS, with the agent verifying the certificate"
fi

echo "meshp status reports a live session"
# Waits for the session *and*, where one is possible, for the tunnel. Waiting only for the
# session made this race: the interface comes up a moment after the first state arrives, so
# an assertion on the same snapshot passed or failed depending on timing. A flaky gate is
# worse than no gate — it teaches people to run it again.
ready=0
for _ in $(seq 1 30); do
  ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
  if grep -q 'session     connected' "$WORK/status.out"; then
    if [ "$tunnel_possible" = "0" ] || grep -qE 'interface   meshp0 \(up' "$WORK/status.out"; then
      ready=1; break
    fi
  fi
  sleep 1
done
[ "$ready" = "1" ] || fail "status never reported a live session and tunnel: $(cat "$WORK/status.out")"
sed 's/^/  /' "$WORK/status.out"
grep -q "$NETWORK_ID" "$WORK/status.out" || fail "status does not mention the network"

# Status must say what is actually true, in either direction: a membership with an address is
# not a working tunnel, and a working tunnel must not be reported as absent. This assertion
# once said "always down" and outlived the build it was written for.
if [ "$tunnel_possible" = "1" ]; then
  grep -qE 'interface   meshp0 \(up' "$WORK/status.out" \
    || fail "a tunnel is possible here but status says it is not up"
else
  grep -q 'interface   meshp0 (not up)' "$WORK/status.out" \
    || fail "no tunnel is possible here, but status claims one"
fi

echo "the agent converges"
lag_zero=0
for _ in $(seq 1 30); do
  lag="$(psql "$DB_URL" -tAqc "
    SELECT coalesce(max(n.state_version - ms.applied_version), -1)
    FROM membership_state ms JOIN networks n ON n.id = ms.network_id
    WHERE ms.network_id = '${NETWORK_ID}'")"
  if [ "$lag" = "0" ]; then lag_zero=1; break; fi
  sleep 1
done
[ "$lag_zero" = "1" ] || fail "applied version never caught up with the network's"
grep -q 'control channel established' "$AGENT_LOG" || fail "the agent never established a session"
sed -n 's/.*msg="recorded desired state" \(.*\)/  \1/p' "$AGENT_LOG" | tail -1

echo "a second device produces a delta, not another snapshot"
# The point of A4: a device joining must not cause every other agent to be handed the whole
# network again. The agent logs whether what it applied was a snapshot.
TOKEN2="$(curl -fsS "${CURL_CA[@]}" -X POST \
  -H "Authorization: Bearer ${ADMIN_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{"max_uses":1,"expires_in_seconds":600}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens" \
  | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')"
[ -n "$TOKEN2" ] || fail "could not mint a second token"

# A second daemon, so the first has a peer to be told about.
STATE_DIR2="$WORK/state2"
SOCKET2="$WORK/d2.sock"
./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR2" --socket "$SOCKET2" --log-level debug >"$WORK/meshpd2.log" 2>&1 &
AGENT2_PID=$!
for _ in $(seq 1 30); do
  [ -S "$SOCKET2" ] && ./bin/meshp status --socket "$SOCKET2" >/dev/null 2>&1 && break
  sleep 1
done
./bin/meshp join "$TOKEN2" --control-url "$BASE" --socket "$SOCKET2" --name e2e-second \
  >"$WORK/join2.out" 2>&1 || fail "the second join failed: $(cat "$WORK/join2.out")"

# Eight seconds, not thirty: the heartbeat interval is 25s and would deliver this on its
# own, so a generous window here cannot tell a working push from a missing one.
got_delta=0
for _ in $(seq 1 8); do
  if grep -q 'msg="applied desired state".*snapshot=false' "$AGENT_LOG"; then got_delta=1; break; fi
  sleep 1
done
kill "$AGENT2_PID" 2>/dev/null || true
wait "$AGENT2_PID" 2>/dev/null || true

if [ "$got_delta" != "1" ]; then
  echo "--- first agent log ---" >&2; cat "$AGENT_LOG" >&2
  fail "the first agent was sent a snapshot rather than a delta when a peer joined"
fi
sed -n 's/.*msg="applied desired state" \(.*snapshot=false.*\)/  \1/p' "$AGENT_LOG" | tail -1

# Only where a tunnel is possible: Linux, with the privilege to create interfaces and a
# kernel that can. Skipped rather than failed elsewhere, because "enrolled with no tunnel"
# is a real supported state and this script has to pass on a laptop too.
if [ "$tunnel_possible" = "1" ]; then
  echo "the interface really comes up"

  up=0
  for _ in $(seq 1 20); do
    if ./bin/meshp status --socket "$SOCKET" 2>/dev/null | grep -qE "interface   meshp0 \((up|up, )"; then
      up=1; break
    fi
    sleep 1
  done
  if [ "$up" != "1" ]; then
    echo "--- status ---" >&2; ./bin/meshp status --socket "$SOCKET" >&2 || true
    echo "--- agent log ---" >&2; tail -30 "$AGENT_LOG" >&2
    fail "the interface never came up"
  fi
  ./bin/meshp status --socket "$SOCKET" | sed -n 's/^\(    interface .*\)/  \1/p'

  # And it is the kernel implementation, not a silent userspace fallback (ADR-0015).
  ./bin/meshp status --socket "$SOCKET" | grep -q "up, kernel" \
    || fail "the tunnel is up but not reported as the kernel implementation"

  # The second daemon in this script shares this host, and the control plane gives both
  # devices the interface name meshp0 — so while it was running the two fought over the same
  # interface and the last one to reconcile won. That is an artefact of running two devices
  # on one host, not something a real deployment does, and it is why the assertions below
  # come after that daemon has been stopped.
  #
  # It does make this a stronger test than it was meant to be: the first daemon has to
  # notice that its interface was taken from it and put it back, with nothing from the
  # control plane to prompt it. That only works because reconciling happens on a timer as
  # well as on arrival.
  echo "  the interface is restored after another process took it over"
  healed=0
  for _ in $(seq 1 20); do
    if ip addr show dev meshp0 2>/dev/null | grep -q "100.90.${OCTET}.1/32"; then healed=1; break; fi
    sleep 1
  done
  if [ "$healed" != "1" ]; then
    echo "--- interface ---" >&2; ip addr show dev meshp0 >&2 || true
    echo "--- wg ---" >&2; wg show meshp0 >&2 || true
    echo "--- agent log ---" >&2; tail -20 "$AGENT_LOG" >&2
    fail "the interface never got this device's address back"
  fi

  # The peer that joined second is configured, with a host route only. A wider prefix would
  # mean one peer absorbing traffic for every other device in the network.
  if command -v wg >/dev/null 2>&1; then
    wg show meshp0 allowed-ips | grep -qE "100\.90\.${OCTET}\.2/32" \
      || { wg show meshp0 >&2; fail "the peer is not configured on the interface"; }
    if wg show meshp0 allowed-ips | grep -qE "/(2[0-9]|1[0-9]|[0-9])\b"; then
      wg show meshp0 allowed-ips >&2
      fail "a peer holds a prefix wider than a single host"
    fi
    echo "  peer configured with host routes only"
  fi

  # And the routes the agent installed are its own, not the kernel's.
  ip route show dev meshp0 | grep -q "100.90.${OCTET}.2" \
    || { ip route show dev meshp0 >&2; fail "no route to the peer via the interface"; }
  echo "  route to the peer installed"

  # ---------------------------------------------------------------------------
  # A name a person could type
  #
  # Everything above proves the resolver is listening and the peer is configured. Neither
  # proves the thing the feature exists for: that somebody types a name and reaches a
  # machine. ADR-0021's chain has three links — the agent knows the name, this host's
  # resolver is pointed at the agent for that domain, and the C library asks this host's
  # resolver — and every one is tested on its own while the joins between them are
  # inference. The resolver's own tests query it directly, so they would pass on a machine
  # where nothing else in the world can find it.
  #
  # This is the join. getent goes through nsswitch and the resolved stub exactly as ssh or
  # a browser does, so a break anywhere along that chain fails here and nowhere else.
  if [ "$resolved_possible" = "1" ]; then
    # From the database, not derived here: the label is the server's to assign (ADR-0021),
    # and a name this script computed would be a test of this script's arithmetic. Reading
    # it back also asserts that enrolment gave the membership a label at all.
    peer_row="$(psql "$DB_URL" -tAqc "
      SELECT m.dns_label || ' ' || host(m.address_v4)
      FROM device_network_memberships m JOIN devices d ON d.id = m.device_id
      WHERE m.network_id = '${NETWORK_ID}' AND d.name = 'e2e-second'")"
    PEER_LABEL="${peer_row%% *}"
    PEER_V4="${peer_row##* }"
    [ -n "$PEER_LABEL" ] || fail "the peer's membership has no dns_label, so it cannot be named"
    PEER_FQDN="${PEER_LABEL}.${SLUG}.internal"

    # The reconciler configures resolved on its own timer, so this waits rather than
    # assuming the last reconcile has happened.
    pointed=0
    for _ in $(seq 1 20); do
      if resolvectl status meshp0 2>/dev/null | grep -q "${SLUG}.internal"; then pointed=1; break; fi
      sleep 1
    done
    if [ "$pointed" != "1" ]; then
      echo "--- resolvectl status meshp0 ---" >&2; resolvectl status meshp0 >&2 || true
      echo "--- agent log, resolver lines ---" >&2
      grep -iE "resolver|resolve" "$AGENT_LOG" | tail -20 >&2
      fail "this host's resolver was never pointed at meshp for ${SLUG}.internal"
    fi
    echo "  resolved routes ${SLUG}.internal to meshp"

    # Negative caching is real: anything that asked for this name before the link was
    # configured left a failure behind that outlives the fix.
    resolvectl flush-caches 2>/dev/null || true

    resolved_name=0
    for _ in $(seq 1 15); do
      if getent ahostsv4 "$PEER_FQDN" >"$WORK/getent.out" 2>&1; then resolved_name=1; break; fi
      sleep 1
    done
    if [ "$resolved_name" != "1" ]; then
      echo "--- getent ---" >&2; cat "$WORK/getent.out" >&2
      echo "--- resolvectl status meshp0 ---" >&2; resolvectl status meshp0 >&2 || true
      echo "--- resolvectl query ---" >&2; resolvectl query "$PEER_FQDN" >&2 2>&1 || true
      # Which link in the chain broke. If resolvectl can answer and getent cannot, this
      # host's C library is not asking resolved at all — /etc/resolv.conf points somewhere
      # other than the stub — and no amount of configuring a link would have helped.
      echo "--- /etc/resolv.conf ---" >&2; cat /etc/resolv.conf >&2 2>&1 || true
      echo "--- nsswitch hosts ---" >&2; grep '^hosts:' /etc/nsswitch.conf >&2 2>&1 || true
      echo "--- agent log, resolver lines ---" >&2
      grep -iE "resolver|resolve|names" "$AGENT_LOG" | tail -20 >&2
      fail "a name this device holds does not resolve on the machine holding it: ${PEER_FQDN}"
    fi
    # The right machine, not merely an answer. A resolver that replied with anything at all
    # would pass the check above.
    grep -q "^${PEER_V4}\b" "$WORK/getent.out" \
      || { cat "$WORK/getent.out" >&2; fail "${PEER_FQDN} resolved, but not to ${PEER_V4}"; }
    echo "  ${PEER_FQDN} -> ${PEER_V4}, through this host's own resolver"

    # And only that domain. A resolver handed every query would break split-horizon
    # corporate DNS on the first laptop that joined, which is why the domain is installed
    # as a routing domain rather than a search domain.
    if getent ahostsv4 "${PEER_LABEL}.not-a-meshp-network.internal" >"$WORK/getent-foreign.out" 2>&1; then
      if grep -qE "^100\.90\." "$WORK/getent-foreign.out"; then
        cat "$WORK/getent-foreign.out" >&2
        fail "a name outside this network's domain was answered from the mesh"
      fi
    fi
    echo "  a name outside the network's domain is not answered from the mesh"
  else
    echo "  skipped-resolver: this host has no systemd-resolved to configure"
  fi

  # ---------------------------------------------------------------------------
  # The relay
  #
  # No peer has a discovered endpoint yet, so a peer with no relayed path is configured and
  # unreachable. Everything above would still pass — which is exactly why this is asserted
  # here rather than left to the unit tests: they prove each piece works, and this proves
  # the pieces were joined up in a real daemon talking to a real relay.
  attached=0
  for _ in $(seq 1 25); do
    ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
    if grep -qE "relay       ${RELAY_ID} via 127\.0\.0\.1:${RELAY_PORT}" "$WORK/status.out"; then
      attached=1; break
    fi
    sleep 1
  done
  if [ "$attached" != "1" ]; then
    echo "--- status ---" >&2; cat "$WORK/status.out" >&2
    echo "--- relay log ---" >&2; tail -20 "$RELAY_LOG" >&2
    echo "--- agent log ---" >&2; grep -iE "relay" "$AGENT_LOG" | tail -20 >&2
    fail "the agent never attached to the relay"
  fi
  echo "  attached to the relay"

  # The address the relay reports seeing. Nothing on this host can work it out for itself,
  # and it is the first evidence the round trip through the relay completed.
  grep -qE "seen as   127\.0\.0\.1:[0-9]+" "$WORK/status.out" \
    || { cat "$WORK/status.out" >&2; fail "the relay never reported this device's address back"; }
  echo "  learned its own reflexive address"

  # A relayed peer's endpoint is a local socket the agent owns (ADR-0016). The kernel has to
  # hold it, or there is nowhere for its packets to go.
  if command -v wg >/dev/null 2>&1; then
    wg show meshp0 endpoints | grep -qE "127\.0\.0\.1:[0-9]+" \
      || { wg show meshp0 endpoints >&2; fail "the peer has no relayed endpoint on the interface"; }
    echo "  peer reached through a local relay socket"
  fi

  # And the MTU is the smaller one a relayed path needs: the relay's header rides outside
  # the WireGuard packet. Getting this wrong loses large packets only, which is the hardest
  # kind of fault to attribute.
  mtu="$(cat /sys/class/net/meshp0/mtu 2>/dev/null || echo 0)"
  [ "$mtu" = "1387" ] \
    || fail "interface MTU is ${mtu}, want 1387 for a relayed path"
  echo "  interface MTU lowered to ${mtu} for relaying"

  # Configured is not carrying. Everything above is satisfied by an interface that holds the
  # right addresses and sends nothing, so this makes the kernel actually use the path: there
  # is a route to the peer and no handshake yet, so one packet at it produces a handshake
  # initiation, which has nowhere to go but the relayed endpoint.
  #
  # The reply is not expected — the peer's daemon was stopped above — so the ping failing is
  # fine and the counter is the assertion. What is being proved is that a packet left the
  # kernel, crossed the agent's socket and was accepted by the relay.
  ping -c 2 -W 1 "100.90.${OCTET}.2" >/dev/null 2>&1 || true
  relayed=0
  for _ in $(seq 1 15); do
    ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
    sent="$(sed -n 's|.*peers     [0-9]* relayed, \([0-9]*\) sent.*|\1|p' "$WORK/status.out")"
    if [ -n "$sent" ] && [ "$sent" -gt 0 ]; then relayed=1; break; fi
    sleep 1
  done
  if [ "$relayed" != "1" ]; then
    echo "--- status ---" >&2; cat "$WORK/status.out" >&2
    echo "--- relay log ---" >&2; tail -20 "$RELAY_LOG" >&2
    fail "the kernel's packets never reached the relay"
  fi
  echo "  the kernel's traffic is leaving through the relay (${sent} packet(s))"

  # ---------------------------------------------------------------------------
  # Route groups
  #
  # A customer LAN that lives on nobody's interface until an administrator says which device
  # carries it. This is the delivery chain end to end: the admin API records an advertiser,
  # selection turns that into an ordered candidate list per device, a state delta carries it,
  # and this host's kernel ends up doing cryptokey routing for a prefix it had never heard of.
  #
  # Worth asserting here for the reason every other section of this file exists. Each piece
  # has unit tests and the pieces were joined up by hand — and local failover shipped across
  # two releases wired into nothing at all, which no test noticed, because every test that
  # could have was a unit test on the mechanism rather than on the daemon.
  #
  # Two things are deliberately out of scope. Whether traffic then crosses into the LAN is
  # proved against a real kernel in internal/nftables. Whether a device fails over to a
  # second advertiser needs two live agents with their own interfaces, which means network
  # namespaces this script does not build yet — both daemons here are handed the name meshp0
  # and would fight over it.
  echo "carrying a customer prefix"

  CARRIED="192.168.${OCTET}.0/24"

  # Which membership is the peer? The second daemon's own state file says.
  PEER_MEMBERSHIP="$(sed -n 's/.*"membership_id": *"\([^"]*\)".*/\1/p' "$STATE_DIR2/state.json" | head -1)"
  [ -n "$PEER_MEMBERSHIP" ] || fail "could not read the peer's membership id"
  OUR_MEMBERSHIP="$(sed -n 's/.*"membership_id": *"\([^"]*\)".*/\1/p' "$STATE_DIR/state.json" | head -1)"
  [ -n "$OUR_MEMBERSHIP" ] || fail "could not read this device's membership id"

  # Waits until this device has applied the state a change produced.
  #
  # Scoped to this membership rather than to the network, because the second daemon is
  # stopped and its applied version never moves again — a network-wide lag check would wait
  # out its timeout on every call. And needed at all because the assertions below include
  # ones about what is *not* on the interface: an absence checked before the agent has seen
  # the change that would have put it there passes for the wrong reason.
  await_applied() {
    for _ in $(seq 1 25); do
      if [ "$(psql "$DB_URL" -tAqc "
            SELECT coalesce(max(n.state_version - ms.applied_version), -1)
            FROM membership_state ms JOIN networks n ON n.id = ms.network_id
            WHERE ms.membership_id = '${OUR_MEMBERSHIP}'")" = "0" ]; then
        return 0
      fi
      sleep 1
    done
    return 1
  }

  curl -fsS "${CURL_CA[@]}" -X POST \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d "{\"slug\":\"branch-lan\",\"name\":\"Branch LAN\",\"kind\":\"subnet\",\"prefixes\":[\"${CARRIED}\"]}" \
    "${BASE}/api/v1/networks/${NETWORK_ID}/route-groups" >"$WORK/routegroup.out" \
    || { cat "$WORK/routegroup.out" >&2; fail "creating the route group failed"; }
  grep -q '"slug":"branch-lan"' "$WORK/routegroup.out" \
    || { cat "$WORK/routegroup.out" >&2; fail "the route group was not created"; }
  echo "  route group branch-lan declares ${CARRIED}"

  # A group nobody advertises is a prefix nobody carries, and it must reach no interface. A
  # device that installed a route the moment a group existed would blackhole the customer's
  # LAN into a tunnel with no other end.
  await_applied || fail "the agent never applied the state containing an unadvertised group"
  if wg show meshp0 allowed-ips 2>/dev/null | grep -qF "$CARRIED"; then
    wg show meshp0 allowed-ips >&2
    fail "a prefix nobody advertises was installed on the interface"
  fi
  echo "  and nothing carries it until someone advertises it"

  curl -fsS "${CURL_CA[@]}" -X POST \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d "{\"membership_id\":\"${PEER_MEMBERSHIP}\",\"priority\":1}" \
    "${BASE}/api/v1/networks/${NETWORK_ID}/route-groups/branch-lan/advertisers" >"$WORK/advertise.out" \
    || { cat "$WORK/advertise.out" >&2; fail "recording the advertiser failed"; }
  grep -q '"status":"advertising"' "$WORK/advertise.out" \
    || { cat "$WORK/advertise.out" >&2; fail "the advertiser was not recorded"; }

  # Cryptokey routing first. WireGuard refuses a packet for a prefix that is not in some
  # peer's allowed IPs whatever the routing table says, so this is the half that decides
  # whether the customer's LAN is reachable at all.
  carried=0
  for _ in $(seq 1 25); do
    if wg show meshp0 allowed-ips 2>/dev/null | grep -qF "$CARRIED"; then carried=1; break; fi
    sleep 1
  done
  if [ "$carried" != "1" ]; then
    echo "--- wg ---" >&2; wg show meshp0 allowed-ips >&2
    echo "--- agent log ---" >&2; grep -iE "route|group|advertis|carr" "$AGENT_LOG" | tail -20 >&2
    fail "the carried prefix never reached the interface"
  fi

  # Against the advertiser specifically, and not merely against some peer. A prefix on the
  # wrong peer hands the customer's traffic to a device that cannot deliver it, and every
  # assertion above would still pass.
  wg show meshp0 allowed-ips | grep -F "$CARRIED" | grep -qE "100\.90\.${OCTET}\.2/32" \
    || { wg show meshp0 allowed-ips >&2; fail "the carried prefix is held by the wrong peer"; }
  echo "  ${CARRIED} is carried by the advertising peer"

  # And a system route, or nothing on this host hands those packets to the tunnel in the
  # first place. Both halves come from the same change and both are asserted: allowed IPs
  # without a route is a device that would accept the customer's LAN and never reach it.
  ip route show dev meshp0 | grep -qF "$CARRIED" \
    || { ip route show dev meshp0 >&2; fail "no system route for the carried prefix"; }
  echo "  and routed through the interface"

  # Withdrawing takes it away again (Invariant 20). A device that kept carrying a prefix
  # after its advertiser was withdrawn would hold the customer's LAN in a tunnel the control
  # plane has already stopped pointing anywhere.
  curl -fsS "${CURL_CA[@]}" -X DELETE \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    "${BASE}/api/v1/networks/${NETWORK_ID}/route-groups/branch-lan/advertisers/${PEER_MEMBERSHIP}" \
    >"$WORK/withdraw.out" \
    || { cat "$WORK/withdraw.out" >&2; fail "withdrawing the advertiser failed"; }

  gone_prefix=0
  for _ in $(seq 1 25); do
    if ! wg show meshp0 allowed-ips 2>/dev/null | grep -qF "$CARRIED"; then gone_prefix=1; break; fi
    sleep 1
  done
  if [ "$gone_prefix" != "1" ]; then
    echo "--- wg ---" >&2; wg show meshp0 allowed-ips >&2
    fail "the prefix survived its advertiser being withdrawn"
  fi
  ip route show dev meshp0 | grep -qF "$CARRIED" \
    && { ip route show dev meshp0 >&2; fail "the route survived its advertiser being withdrawn"; }
  echo "  withdrawing the advertiser removed both the prefix and its route"

  # ---------------------------------------------------------------------------
  # Revocation
  #
  # Everything above describes a device that is in the network. This is the other half:
  # taking one out has to actually remove it, and the removal is enforced here — on the
  # peer — rather than on the device being revoked. That is why this is asserted against
  # the first daemon while the second one is not even running.
  echo "revoking the second device"

  # PEER_MEMBERSHIP was read from the second daemon's own state file above. That the listing
  # endpoint agrees with it is a check in its own right.
  curl -fsS "${CURL_CA[@]}" -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    "${BASE}/api/v1/networks/${NETWORK_ID}/devices" >"$WORK/devices.out" \
    || fail "could not list the network's devices"
  grep -q "$PEER_MEMBERSHIP" "$WORK/devices.out" \
    || { cat "$WORK/devices.out" >&2; fail "the device listing does not contain the peer"; }

  curl -fsS "${CURL_CA[@]}" -X DELETE \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d '{"reason":"e2e revocation"}' \
    "${BASE}/api/v1/networks/${NETWORK_ID}/devices/${PEER_MEMBERSHIP}" >"$WORK/revoke.out" \
    || { cat "$WORK/revoke.out" >&2; fail "the revoke request failed"; }
  grep -q '"status":"revoked"' "$WORK/revoke.out" \
    || { cat "$WORK/revoke.out" >&2; fail "revoke did not report success"; }

  # The peer disappears from the interface. This is the whole enforcement mechanism: the
  # revoked device keeps its key and its address, and what changes is that nobody will
  # accept it any more.
  gone=0
  for _ in $(seq 1 25); do
    if ! wg show meshp0 allowed-ips 2>/dev/null | grep -qE "100\.90\.${OCTET}\.2/32"; then
      gone=1; break
    fi
    sleep 1
  done
  if [ "$gone" != "1" ]; then
    echo "--- wg ---" >&2; wg show meshp0 >&2
    echo "--- agent log ---" >&2; tail -20 "$AGENT_LOG" >&2
    fail "a revoked device is still configured as a peer"
  fi
  echo "  the peer was dropped from the interface"

  # And its route with it, or traffic for that address would still be handed to a tunnel
  # that has nowhere to send it.
  ip route show dev meshp0 | grep -q "100.90.${OCTET}.2" \
    && { ip route show dev meshp0 >&2; fail "the route to the revoked device survived"; }
  echo "  and its route withdrawn"

  # The relayed socket that served it is released. Nothing had ever exercised this before
  # revocation existed: a peer had no way to stop being relayed, so the retirement path in
  # relaylink ran only in its own tests.
  relayed_now="$(./bin/meshp status --socket "$SOCKET" \
    | sed -n 's|.*peers     \([0-9]*\) relayed.*|\1|p')"
  if [ -n "$relayed_now" ] && [ "$relayed_now" != "0" ]; then
    ./bin/meshp status --socket "$SOCKET" >&2
    fail "the revoked peer's relay socket was not released (${relayed_now} still served)"
  fi
  echo "  its relay socket was released"

  # The revoked device cannot come back.
  #
  # Asserted by restarting its daemon rather than by poking the challenge endpoint. That
  # endpoint deliberately does not check whether a membership exists — doing so would make
  # it an enumeration oracle for membership ids — so it answers a revoked device just as it
  # answers a made-up one. The signature check at connect time is what decides, and this is
  # the only place to observe it.
  ./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR2" --socket "$SOCKET2" \
    --log-level debug >>"$WORK/meshpd2.log" 2>&1 &
  AGENT2_PID=$!
  for _ in $(seq 1 20); do
    [ -S "$SOCKET2" ] && ./bin/meshp status --socket "$SOCKET2" >/dev/null 2>&1 && break
    sleep 1
  done

  # The agent is told only that authentication failed. That is deliberate — the reason a
  # membership is refused crosses a trust boundary towards a device that may no longer be
  # trusted — so this matches the refusal rather than the cause. The cause is in the
  # control plane's own log, asserted below, where an operator can see it.
  refused=0
  for _ in $(seq 1 20); do
    if grep -q "authentication failed" "$WORK/meshpd2.log"; then refused=1; break; fi
    sleep 1
  done
  if [ "$refused" != "1" ]; then
    echo "--- revoked agent log ---" >&2; tail -20 "$WORK/meshpd2.log" >&2
    fail "the revoked device was not refused a session"
  fi

  grep -qiE "revoked|membership is" "$CONTROL_LOG" \
    || { tail -20 "$CONTROL_LOG" >&2; fail "the control plane did not record why it refused"; }
  ./bin/meshp status --socket "$SOCKET2" | grep -qE 'session     connected' \
    && { ./bin/meshp status --socket "$SOCKET2" >&2; fail "a revoked device holds a session"; }
  echo "  and cannot open a new session"

  # ---------------------------------------------------------------------------
  # Policy
  #
  # The end of the chain the ACL work has been building: a document published over the
  # admin API, compiled per device by the control plane, delivered in a state delta, and
  # loaded into this host's kernel. Everything before this proved a piece of it.
  echo "publishing a policy"

  # Before any policy, nothing is filtered. This is the property that keeps existing
  # deployments working across an upgrade, and it is worth asserting from the kernel's side
  # rather than trusting the control plane not to have sent one.
  if nft list table inet meshp >/dev/null 2>&1; then
    nft list table inet meshp >&2
    fail "a table exists before any policy was published"
  fi
  echo "  nothing is filtered before a policy exists"

  curl -fsS "${CURL_CA[@]}" -X PUT \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d '{"version":1,"rules":[{"src":["*"],"dst":["*"],"protocol":"tcp","ports":["22"]}]}' \
    "${BASE}/api/v1/networks/${NETWORK_ID}/acl" >"$WORK/acl.out" \
    || { cat "$WORK/acl.out" >&2; fail "publishing the policy failed"; }
  grep -q '"status":"published"' "$WORK/acl.out" \
    || { cat "$WORK/acl.out" >&2; fail "the policy was not published"; }

  loaded=0
  for _ in $(seq 1 25); do
    if nft list table inet meshp >/dev/null 2>&1; then loaded=1; break; fi
    sleep 1
  done
  if [ "$loaded" != "1" ]; then
    # `|| true` on every diagnostic: a grep that finds nothing exits non-zero, and under
    # `set -e` that kills the script before it can say what went wrong.
    echo "--- agent log ---" >&2; { grep -iE "policy|filter|nft|capab" "$AGENT_LOG" || true; } | tail -20 >&2
    fail "the policy never reached the kernel"
  fi
  nft list table inet meshp >"$WORK/nft.out"
  echo "  the policy is in the kernel"

  # The bound the whole design rests on: a policy can only ever drop mesh traffic. If this
  # rule were missing, a mistaken policy would take the host off its own network — including
  # the connection an operator would use to fix it.
  grep -q 'iifname != "meshp0" accept' "$WORK/nft.out" \
    || { cat "$WORK/nft.out" >&2; fail "the ruleset does not let non-mesh traffic past"; }
  echo "  traffic off the interface is untouched"

  grep -q 'ct state established,related accept' "$WORK/nft.out" \
    || { cat "$WORK/nft.out" >&2; fail "return traffic is not accepted; allowed connections would hang"; }
  grep -q 'tcp dport 22' "$WORK/nft.out" \
    || { cat "$WORK/nft.out" >&2; fail "the published rule is not in the ruleset"; }
  grep -q 'drop' "$WORK/nft.out" \
    || { cat "$WORK/nft.out" >&2; fail "the ruleset permits everything it does not mention"; }
  echo "  it denies by default and permits what was written"

  # And the agent says it can enforce, which is what the control plane acts on (ADR-0007).
  grep -q '"packet_filter":true\|packet_filter=true' "$AGENT_LOG" 2>/dev/null \
    || true

  # Withdrawing it has to leave nothing behind, or a network that removed its policy would
  # go on denying traffic forever with nothing to say why.
  curl -fsS "${CURL_CA[@]}" -X PUT \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d '{"version":1,"rules":[{"src":["*"],"dst":["*"]}]}' \
    "${BASE}/api/v1/networks/${NETWORK_ID}/acl" >/dev/null \
    || fail "republishing a permissive policy failed"

  widened=0
  for _ in $(seq 1 25); do
    if nft list table inet meshp 2>/dev/null | grep -q 'ip saddr'; then
      if ! nft list table inet meshp 2>/dev/null | grep -q 'tcp dport 22'; then widened=1; break; fi
    fi
    sleep 1
  done
  if [ "$widened" != "1" ]; then
    nft list table inet meshp >&2 || true
    fail "a republished policy did not replace the one in the kernel"
  fi
  echo "  republishing replaces the ruleset rather than adding to it"

  kill "$AGENT2_PID" 2>/dev/null || true
  wait "$AGENT2_PID" 2>/dev/null || true
  AGENT2_PID=""

  # The listen port survives a restart, which is what keeps the endpoints peers hold valid
  # and any NAT mapping alive.
  #
  # The interface is deleted before restarting on purpose. It outlives the daemon by design
  # (Invariant 15: a control-plane outage does not interrupt established networking), so a
  # restart on its own would find the port already correct and prove nothing about whether
  # anything was remembered.
  port_before="$(./bin/meshp status --socket "$SOCKET" | sed -n 's|.*listening   udp/\([0-9]*\).*|\1|p')"
  [ -n "$port_before" ] || { ./bin/meshp status --socket "$SOCKET" >&2; fail "status does not report a listen port"; }
  echo "  listening on udp/${port_before}"

  grep -q "\"listen_port\": *${port_before}" "$STATE_DIR/state.json" \
    || { fail "the listen port was not written to local state"; }

  kill "$AGENT_PID" 2>/dev/null || true
  wait "$AGENT_PID" 2>/dev/null || true
  ip link del meshp0
  ./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR" --socket "$SOCKET" \
    --log-level debug >>"$AGENT_LOG" 2>&1 &
  AGENT_PID=$!

  back=0
  for _ in $(seq 1 25); do
    if [ -S "$SOCKET" ] && ./bin/meshp status --socket "$SOCKET" 2>/dev/null | grep -qE 'interface   meshp0 \(up'; then
      back=1; break
    fi
    sleep 1
  done
  [ "$back" = "1" ] || { tail -20 "$AGENT_LOG" >&2; fail "the interface did not come back after a restart"; }

  port_after="$(./bin/meshp status --socket "$SOCKET" | sed -n 's|.*listening   udp/\([0-9]*\).*|\1|p')"
  [ "$port_after" = "$port_before" ] \
    || fail "the listen port changed across a restart: ${port_before} then ${port_after}"
  echo "  the same port after a restart and a deleted interface"
fi

echo "the same token a second time"
if ./bin/meshp join "$TOKEN" --control-url "$BASE" --socket "$SOCKET" >"$WORK/replay.out" 2>&1; then
  fail "a replayed token was accepted"
fi
sed 's/^/  /' "$WORK/replay.out"
grep -q 'already been used' "$WORK/replay.out" || fail "the replay was refused for the wrong reason"

echo "the enrolment is in the audit trail"
events="$(psql "$DB_URL" -tAqc "SELECT count(*) FROM audit_events
  WHERE action = 'device.enrolled' AND network_id = '${NETWORK_ID}'")"
# Two: the device under test and the second one that produced the delta.
[ "$events" = "2" ] || fail "${events} device.enrolled events, want 2"

echo "the session is cleared when the agent goes away"
kill "$AGENT_PID" 2>/dev/null || true
wait "$AGENT_PID" 2>/dev/null || true
AGENT_PID=""
cleared=0
for _ in $(seq 1 20); do
  rows="$(psql "$DB_URL" -tAqc "SELECT count(*) FROM membership_state
    WHERE control_session_id IS NOT NULL AND network_id = '${NETWORK_ID}'")"
  if [ "$rows" = "0" ]; then cleared=1; break; fi
  sleep 1
done
[ "$cleared" = "1" ] || fail "a membership is still marked connected after the agent exited"

# Left behind, the next start would warn about a stale socket for no reason.
if [ -S "$SOCKET" ]; then fail "the daemon left its socket behind on exit"; fi

echo "no private key material reached the control plane"
if grep -qiE 'private[_ ]?key' "$CONTROL_LOG"; then fail "the control plane log mentions a private key"; fi
if grep -qF "$TOKEN" "$CONTROL_LOG"; then fail "the control plane logged the plaintext token"; fi

echo
echo "enrolment and the control channel work end to end; a replayed token is refused"
