#!/usr/bin/env bash
#
# Enrolment and the control channel, end to end, with the real binaries:
#
#   meshpd comes up with no state at all and is still usable
#   a token is minted over the administrative API
#   `meshp join` asks the daemon, which is what generates the keys
#   the keys land with restrictive permissions, written by the daemon
#   `meshp status` reports a live session, and says the tunnel is not up
#   the same token is refused a second time
#   the agent converges: applied version catches up with the network's
#   the session is cleared when the agent exits
#   no private key material appears where it should not
#
# Usage: e2e-enrol.sh <postgres-url>
#
# The unit tests cover each of these against a library. This covers what a person
# actually runs, which is where the wiring mistakes are — flag parsing, file modes,
# socket permissions, exit codes.
set -euo pipefail

DB_URL="${1:?usage: e2e-enrol.sh <postgres-url>}"
PORT="${MESHP_E2E_PORT:-8099}"
BASE="http://127.0.0.1:${PORT}"
ADMIN_TOKEN="e2e-administrative-token-not-a-secret"
SECRET_KEY="e2e-deployment-secret-not-a-secret"

# Short paths on purpose: a unix socket path has a hard limit near 100 bytes, and mktemp
# under a long temporary root can exceed it — which fails with "invalid argument" and no
# hint about why.
WORK="$(mktemp -d /tmp/mpe2e.XXXXXX)"
CONTROL_LOG="$WORK/control.log"
AGENT_LOG="$WORK/meshpd.log"
RELAY_LOG="$WORK/relay.log"
STATE_DIR="$WORK/state"
SOCKET="$WORK/d.sock"
CONTROL_PID=""
AGENT_PID=""
RELAY_PID=""

# A relay of this deployment's own, on a loopback port. Every peer is relayed until
# discovery exists (ADR-0002), so without one the agent's peers are configured and
# unreachable — and the assertions below would pass on a mesh that carries nothing.
RELAY_PORT="${MESHP_E2E_RELAY_PORT:-3479}"
RELAY_ID="e2e"

cleanup() {
  [ -n "$AGENT_PID" ] && kill "$AGENT_PID" 2>/dev/null || true
  [ -n "$RELAY_PID" ] && kill "$RELAY_PID" 2>/dev/null || true
  [ -n "$CONTROL_PID" ] && kill "$CONTROL_PID" 2>/dev/null || true
  rm -rf "$WORK"
}
trap cleanup EXIT

fail() {
  echo "FAIL: $*" >&2
  echo "--- control plane log ---" >&2; cat "$CONTROL_LOG" >&2 2>/dev/null || true
  echo "--- relay log ---" >&2; cat "$RELAY_LOG" >&2 2>/dev/null || true
  echo "--- agent log ---" >&2; cat "$AGENT_LOG" >&2 2>/dev/null || true
  exit 1
}

mode_of() { stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"; }

for binary in ./bin/meshp ./bin/meshpd ./bin/meshp-control ./bin/meshp-relay; do
  [ -x "$binary" ] || fail "$binary is missing; run make build"
done

# One keypair: the control plane signs relay tokens with the private half and the relay
# verifies them with the public half. Generated by the same command an operator runs, so a
# change to its output format fails here rather than in someone's deployment.
./bin/meshp-control --generate-relay-key >"$WORK/relay.env" \
  || fail "could not generate a relay keypair"
RELAY_SIGNING_KEY="$(sed -n 's/^MESHP_RELAY_SIGNING_KEY=//p' "$WORK/relay.env")"
RELAY_ISSUER_KEY="$(sed -n 's/^MESHP_RELAY_ISSUER_KEY=//p' "$WORK/relay.env")"
[ -n "$RELAY_SIGNING_KEY" ] && [ -n "$RELAY_ISSUER_KEY" ] \
  || { cat "$WORK/relay.env" >&2; fail "the relay keygen output did not contain both keys"; }

echo "starting meshp-relay on 127.0.0.1:${RELAY_PORT}"
MESHP_RELAY_LISTEN="127.0.0.1:${RELAY_PORT}" \
MESHP_RELAY_ISSUER_KEY="$RELAY_ISSUER_KEY" \
MESHP_RELAY_ADMIN_ADDR="127.0.0.1:9099" \
  ./bin/meshp-relay >"$RELAY_LOG" 2>&1 &
RELAY_PID=$!

echo "starting meshp-control on ${BASE}"
MESHP_DATABASE_URL="$DB_URL" \
MESHP_LISTEN_ADDR="127.0.0.1:${PORT}" \
MESHP_SECRET_KEY="$SECRET_KEY" \
MESHP_ADMIN_TOKEN="$ADMIN_TOKEN" \
MESHP_RELAY_SIGNING_KEY="$RELAY_SIGNING_KEY" \
MESHP_RELAYS="${RELAY_ID}=127.0.0.1:${RELAY_PORT}" \
  ./bin/meshp-control >"$CONTROL_LOG" 2>&1 &
CONTROL_PID=$!

for _ in $(seq 1 30); do
  curl -fsS "${BASE}/readyz" >/dev/null 2>&1 && break
  sleep 1
done
curl -fsS "${BASE}/readyz" >/dev/null 2>&1 || fail "control plane never became ready"

echo "starting meshpd with no state at all"
# Deliberately before enrolment. An agent that gives up when it has nothing to do cannot
# be joined without restarting a service, which is a paper cut people script around.
./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR" --socket "$SOCKET" --log-level debug >"$AGENT_LOG" 2>&1 &
AGENT_PID=$!

for _ in $(seq 1 30); do
  [ -S "$SOCKET" ] && ./bin/meshp status --socket "$SOCKET" >/dev/null 2>&1 && break
  sleep 1
done
./bin/meshp status --socket "$SOCKET" >"$WORK/status-before.out" 2>&1 \
  || fail "the daemon never answered on its socket"
grep -q 'not enrolled' "$WORK/status-before.out" \
  || fail "an unenrolled daemon did not say so: $(cat "$WORK/status-before.out")"
echo "  socket answers: $(head -1 "$WORK/status-before.out")"

echo "the socket is owner-only"
# A privilege boundary: anything that can reach this socket can enrol the device and,
# once tunnels exist, decide where its traffic goes.
socket_mode="$(mode_of "$SOCKET")"
[ "$socket_mode" = "600" ] || fail "the socket is ${socket_mode}, want 600"
echo "  0${socket_mode}"

echo "seeding a network with address pools"
# A distinct slug and address pool per run. Seeding fixed names made this script pass exactly
# once against any given database and fail on every rerun, which CI never noticed because it
# gets a fresh Postgres each time. A test that only works on a virgin database is one nobody
# can reproduce locally.
RUN_ID="$$"
SLUG="e2e-${RUN_ID}"
# The third octet keeps concurrent and repeated runs out of each other's pools.
OCTET="$(( RUN_ID % 250 + 1 ))"
# Explicit casts: inside a UNION the literals have no inferable type, and cidr will not
# accept text.
NETWORK_ID="$(psql "$DB_URL" -tAqc "
  WITH o AS (INSERT INTO organizations (slug, name) VALUES ('${SLUG}', 'End To End ${RUN_ID}') RETURNING id),
       n AS (INSERT INTO networks (organization_id, slug, name) SELECT id, '${SLUG}', 'End To End ${RUN_ID}' FROM o RETURNING id),
       p AS (INSERT INTO address_pools (network_id, prefix, family, purpose)
             SELECT id, '100.90.${OCTET}.0/24'::cidr, 4, 'device' FROM n
             UNION ALL
             SELECT id, ('fd7c:6d65:7368:' || to_hex(${OCTET}) || '::/120')::cidr, 6, 'device' FROM n
             RETURNING network_id)
  SELECT DISTINCT network_id FROM p")"
[ -n "$NETWORK_ID" ] || fail "could not seed a network"
echo "  network ${NETWORK_ID}"

echo "minting an enrolment token"
MINT="$(curl -fsS -X POST \
  -H "Authorization: Bearer ${ADMIN_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{"max_uses":1,"expires_in_seconds":600,"tags":["e2e"]}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens")"
TOKEN="$(printf '%s' "$MINT" | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')"
[ -n "$TOKEN" ] || fail "no token in the mint response: $MINT"
case "$TOKEN" in
  meshp_tok_*) ;;
  *) fail "token does not carry the expected prefix: $TOKEN" ;;
esac
echo "  minted ${TOKEN:0:18}…"

echo "the administrative API refuses an unauthenticated caller"
status="$(curl -s -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' -d '{}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens")"
[ "$status" = "401" ] || fail "minting without a token returned ${status}, want 401"

echo "meshp join"
./bin/meshp join "$TOKEN" --control-url "$BASE" --socket "$SOCKET" --name e2e-device \
  >"$WORK/join.out" 2>&1 || fail "join failed: $(cat "$WORK/join.out")"
sed 's/^/  /' "$WORK/join.out"
grep -q 'enrolled in network' "$WORK/join.out" || fail "join did not report success"
grep -qE "address     100\.90\.${OCTET}\." "$WORK/join.out" || fail "join reported no IPv4 address"

echo "the keys were written by the daemon, and only it can read them"
[ -f "$STATE_DIR/state.json" ] || fail "no state file was written"
file_mode="$(mode_of "$STATE_DIR/state.json")"
dir_mode="$(mode_of "$STATE_DIR")"
[ "$file_mode" = "600" ] || fail "state file is ${file_mode}, want 600"
[ "$dir_mode" = "700" ] || fail "state directory is ${dir_mode}, want 700"
echo "  file 0${file_mode}, directory 0${dir_mode}"

echo "no private key crossed the socket or reached a log"
# Invariant 1. The CLI asked the daemon to enrol; it must not have been handed anything
# secret in return, and the control plane must never have seen one.
if grep -qiE 'private' "$WORK/join.out"; then fail "the CLI's output mentions a private key"; fi
priv="$(sed -n 's/.*"wireguard_private_key": *"\([^"]*\)".*/\1/p' "$STATE_DIR/state.json" | head -1)"
[ -n "$priv" ] || fail "could not read the stored private key to check for leaks"
if grep -qF "$priv" "$WORK/join.out"; then fail "the CLI printed the WireGuard private key"; fi
if grep -qF "$priv" "$CONTROL_LOG"; then fail "the control plane logged the WireGuard private key"; fi

# Whether a tunnel is possible here at all, decided once and reused. Deciding it rather than
# assuming it is why this section survives both a laptop and a privileged Linux runner.
tunnel_possible=0
if [ "$(uname -s)" = "Linux" ] && [ "$(id -u)" = "0" ] && ip link add dev wgprobe0 type wireguard 2>/dev/null; then
  ip link del dev wgprobe0
  tunnel_possible=1
fi

echo "meshp status reports a live session"
# Waits for the session *and*, where one is possible, for the tunnel. Waiting only for the
# session made this race: the interface comes up a moment after the first state arrives, so
# an assertion on the same snapshot passed or failed depending on timing. A flaky gate is
# worse than no gate — it teaches people to run it again.
ready=0
for _ in $(seq 1 30); do
  ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
  if grep -q 'session     connected' "$WORK/status.out"; then
    if [ "$tunnel_possible" = "0" ] || grep -qE 'interface   meshp0 \(up' "$WORK/status.out"; then
      ready=1; break
    fi
  fi
  sleep 1
done
[ "$ready" = "1" ] || fail "status never reported a live session and tunnel: $(cat "$WORK/status.out")"
sed 's/^/  /' "$WORK/status.out"
grep -q "$NETWORK_ID" "$WORK/status.out" || fail "status does not mention the network"

# Status must say what is actually true, in either direction: a membership with an address is
# not a working tunnel, and a working tunnel must not be reported as absent. This assertion
# once said "always down" and outlived the build it was written for.
if [ "$tunnel_possible" = "1" ]; then
  grep -qE 'interface   meshp0 \(up' "$WORK/status.out" \
    || fail "a tunnel is possible here but status says it is not up"
else
  grep -q 'interface   meshp0 (not up)' "$WORK/status.out" \
    || fail "no tunnel is possible here, but status claims one"
fi

echo "the agent converges"
lag_zero=0
for _ in $(seq 1 30); do
  lag="$(psql "$DB_URL" -tAqc "
    SELECT coalesce(max(n.state_version - ms.applied_version), -1)
    FROM membership_state ms JOIN networks n ON n.id = ms.network_id
    WHERE ms.network_id = '${NETWORK_ID}'")"
  if [ "$lag" = "0" ]; then lag_zero=1; break; fi
  sleep 1
done
[ "$lag_zero" = "1" ] || fail "applied version never caught up with the network's"
grep -q 'control channel established' "$AGENT_LOG" || fail "the agent never established a session"
sed -n 's/.*msg="recorded desired state" \(.*\)/  \1/p' "$AGENT_LOG" | tail -1

echo "a second device produces a delta, not another snapshot"
# The point of A4: a device joining must not cause every other agent to be handed the whole
# network again. The agent logs whether what it applied was a snapshot.
TOKEN2="$(curl -fsS -X POST \
  -H "Authorization: Bearer ${ADMIN_TOKEN}" \
  -H 'Content-Type: application/json' \
  -d '{"max_uses":1,"expires_in_seconds":600}' \
  "${BASE}/api/v1/networks/${NETWORK_ID}/enrollment-tokens" \
  | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')"
[ -n "$TOKEN2" ] || fail "could not mint a second token"

# A second daemon, so the first has a peer to be told about.
STATE_DIR2="$WORK/state2"
SOCKET2="$WORK/d2.sock"
./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR2" --socket "$SOCKET2" --log-level debug >"$WORK/meshpd2.log" 2>&1 &
AGENT2_PID=$!
for _ in $(seq 1 30); do
  [ -S "$SOCKET2" ] && ./bin/meshp status --socket "$SOCKET2" >/dev/null 2>&1 && break
  sleep 1
done
./bin/meshp join "$TOKEN2" --control-url "$BASE" --socket "$SOCKET2" --name e2e-second \
  >"$WORK/join2.out" 2>&1 || fail "the second join failed: $(cat "$WORK/join2.out")"

# Eight seconds, not thirty: the heartbeat interval is 25s and would deliver this on its
# own, so a generous window here cannot tell a working push from a missing one.
got_delta=0
for _ in $(seq 1 8); do
  if grep -q 'msg="applied desired state".*snapshot=false' "$AGENT_LOG"; then got_delta=1; break; fi
  sleep 1
done
kill "$AGENT2_PID" 2>/dev/null || true
wait "$AGENT2_PID" 2>/dev/null || true

if [ "$got_delta" != "1" ]; then
  echo "--- first agent log ---" >&2; cat "$AGENT_LOG" >&2
  fail "the first agent was sent a snapshot rather than a delta when a peer joined"
fi
sed -n 's/.*msg="applied desired state" \(.*snapshot=false.*\)/  \1/p' "$AGENT_LOG" | tail -1

# Only where a tunnel is possible: Linux, with the privilege to create interfaces and a
# kernel that can. Skipped rather than failed elsewhere, because "enrolled with no tunnel"
# is a real supported state and this script has to pass on a laptop too.
if [ "$tunnel_possible" = "1" ]; then
  echo "the interface really comes up"

  up=0
  for _ in $(seq 1 20); do
    if ./bin/meshp status --socket "$SOCKET" 2>/dev/null | grep -qE "interface   meshp0 \((up|up, )"; then
      up=1; break
    fi
    sleep 1
  done
  if [ "$up" != "1" ]; then
    echo "--- status ---" >&2; ./bin/meshp status --socket "$SOCKET" >&2 || true
    echo "--- agent log ---" >&2; tail -30 "$AGENT_LOG" >&2
    fail "the interface never came up"
  fi
  ./bin/meshp status --socket "$SOCKET" | sed -n 's/^\(    interface .*\)/  \1/p'

  # And it is the kernel implementation, not a silent userspace fallback (ADR-0015).
  ./bin/meshp status --socket "$SOCKET" | grep -q "up, kernel" \
    || fail "the tunnel is up but not reported as the kernel implementation"

  # The second daemon in this script shares this host, and the control plane gives both
  # devices the interface name meshp0 — so while it was running the two fought over the same
  # interface and the last one to reconcile won. That is an artefact of running two devices
  # on one host, not something a real deployment does, and it is why the assertions below
  # come after that daemon has been stopped.
  #
  # It does make this a stronger test than it was meant to be: the first daemon has to
  # notice that its interface was taken from it and put it back, with nothing from the
  # control plane to prompt it. That only works because reconciling happens on a timer as
  # well as on arrival.
  echo "  the interface is restored after another process took it over"
  healed=0
  for _ in $(seq 1 20); do
    if ip addr show dev meshp0 2>/dev/null | grep -q "100.90.${OCTET}.1/32"; then healed=1; break; fi
    sleep 1
  done
  if [ "$healed" != "1" ]; then
    echo "--- interface ---" >&2; ip addr show dev meshp0 >&2 || true
    echo "--- wg ---" >&2; wg show meshp0 >&2 || true
    echo "--- agent log ---" >&2; tail -20 "$AGENT_LOG" >&2
    fail "the interface never got this device's address back"
  fi

  # The peer that joined second is configured, with a host route only. A wider prefix would
  # mean one peer absorbing traffic for every other device in the network.
  if command -v wg >/dev/null 2>&1; then
    wg show meshp0 allowed-ips | grep -qE "100\.90\.${OCTET}\.2/32" \
      || { wg show meshp0 >&2; fail "the peer is not configured on the interface"; }
    if wg show meshp0 allowed-ips | grep -qE "/(2[0-9]|1[0-9]|[0-9])\b"; then
      wg show meshp0 allowed-ips >&2
      fail "a peer holds a prefix wider than a single host"
    fi
    echo "  peer configured with host routes only"
  fi

  # And the routes the agent installed are its own, not the kernel's.
  ip route show dev meshp0 | grep -q "100.90.${OCTET}.2" \
    || { ip route show dev meshp0 >&2; fail "no route to the peer via the interface"; }
  echo "  route to the peer installed"

  # ---------------------------------------------------------------------------
  # The relay
  #
  # No peer has a discovered endpoint yet, so a peer with no relayed path is configured and
  # unreachable. Everything above would still pass — which is exactly why this is asserted
  # here rather than left to the unit tests: they prove each piece works, and this proves
  # the pieces were joined up in a real daemon talking to a real relay.
  attached=0
  for _ in $(seq 1 25); do
    ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
    if grep -qE "relay       ${RELAY_ID} via 127\.0\.0\.1:${RELAY_PORT}" "$WORK/status.out"; then
      attached=1; break
    fi
    sleep 1
  done
  if [ "$attached" != "1" ]; then
    echo "--- status ---" >&2; cat "$WORK/status.out" >&2
    echo "--- relay log ---" >&2; tail -20 "$RELAY_LOG" >&2
    echo "--- agent log ---" >&2; grep -iE "relay" "$AGENT_LOG" | tail -20 >&2
    fail "the agent never attached to the relay"
  fi
  echo "  attached to the relay"

  # The address the relay reports seeing. Nothing on this host can work it out for itself,
  # and it is the first evidence the round trip through the relay completed.
  grep -qE "seen as   127\.0\.0\.1:[0-9]+" "$WORK/status.out" \
    || { cat "$WORK/status.out" >&2; fail "the relay never reported this device's address back"; }
  echo "  learned its own reflexive address"

  # A relayed peer's endpoint is a local socket the agent owns (ADR-0016). The kernel has to
  # hold it, or there is nowhere for its packets to go.
  if command -v wg >/dev/null 2>&1; then
    wg show meshp0 endpoints | grep -qE "127\.0\.0\.1:[0-9]+" \
      || { wg show meshp0 endpoints >&2; fail "the peer has no relayed endpoint on the interface"; }
    echo "  peer reached through a local relay socket"
  fi

  # And the MTU is the smaller one a relayed path needs: the relay's header rides outside
  # the WireGuard packet. Getting this wrong loses large packets only, which is the hardest
  # kind of fault to attribute.
  mtu="$(cat /sys/class/net/meshp0/mtu 2>/dev/null || echo 0)"
  [ "$mtu" = "1387" ] \
    || fail "interface MTU is ${mtu}, want 1387 for a relayed path"
  echo "  interface MTU lowered to ${mtu} for relaying"

  # Configured is not carrying. Everything above is satisfied by an interface that holds the
  # right addresses and sends nothing, so this makes the kernel actually use the path: there
  # is a route to the peer and no handshake yet, so one packet at it produces a handshake
  # initiation, which has nowhere to go but the relayed endpoint.
  #
  # The reply is not expected — the peer's daemon was stopped above — so the ping failing is
  # fine and the counter is the assertion. What is being proved is that a packet left the
  # kernel, crossed the agent's socket and was accepted by the relay.
  ping -c 2 -W 1 "100.90.${OCTET}.2" >/dev/null 2>&1 || true
  relayed=0
  for _ in $(seq 1 15); do
    ./bin/meshp status --socket "$SOCKET" >"$WORK/status.out" 2>&1 || true
    sent="$(sed -n 's|.*peers     [0-9]* relayed, \([0-9]*\) sent.*|\1|p' "$WORK/status.out")"
    if [ -n "$sent" ] && [ "$sent" -gt 0 ]; then relayed=1; break; fi
    sleep 1
  done
  if [ "$relayed" != "1" ]; then
    echo "--- status ---" >&2; cat "$WORK/status.out" >&2
    echo "--- relay log ---" >&2; tail -20 "$RELAY_LOG" >&2
    fail "the kernel's packets never reached the relay"
  fi
  echo "  the kernel's traffic is leaving through the relay (${sent} packet(s))"

  # ---------------------------------------------------------------------------
  # Revocation
  #
  # Everything above describes a device that is in the network. This is the other half:
  # taking one out has to actually remove it, and the removal is enforced here — on the
  # peer — rather than on the device being revoked. That is why this is asserted against
  # the first daemon while the second one is not even running.
  echo "revoking the second device"

  # Which membership is the peer? The second daemon's own state file says, which is also a
  # check that the listing endpoint agrees with it.
  PEER_MEMBERSHIP="$(sed -n 's/.*"membership_id": *"\([^"]*\)".*/\1/p' "$STATE_DIR2/state.json" | head -1)"
  [ -n "$PEER_MEMBERSHIP" ] || fail "could not read the peer's membership id"

  curl -fsS -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    "${BASE}/api/v1/networks/${NETWORK_ID}/devices" >"$WORK/devices.out" \
    || fail "could not list the network's devices"
  grep -q "$PEER_MEMBERSHIP" "$WORK/devices.out" \
    || { cat "$WORK/devices.out" >&2; fail "the device listing does not contain the peer"; }

  curl -fsS -X DELETE \
    -H "Authorization: Bearer ${ADMIN_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d '{"reason":"e2e revocation"}' \
    "${BASE}/api/v1/networks/${NETWORK_ID}/devices/${PEER_MEMBERSHIP}" >"$WORK/revoke.out" \
    || { cat "$WORK/revoke.out" >&2; fail "the revoke request failed"; }
  grep -q '"status":"revoked"' "$WORK/revoke.out" \
    || { cat "$WORK/revoke.out" >&2; fail "revoke did not report success"; }

  # The peer disappears from the interface. This is the whole enforcement mechanism: the
  # revoked device keeps its key and its address, and what changes is that nobody will
  # accept it any more.
  gone=0
  for _ in $(seq 1 25); do
    if ! wg show meshp0 allowed-ips 2>/dev/null | grep -qE "100\.90\.${OCTET}\.2/32"; then
      gone=1; break
    fi
    sleep 1
  done
  if [ "$gone" != "1" ]; then
    echo "--- wg ---" >&2; wg show meshp0 >&2
    echo "--- agent log ---" >&2; tail -20 "$AGENT_LOG" >&2
    fail "a revoked device is still configured as a peer"
  fi
  echo "  the peer was dropped from the interface"

  # And its route with it, or traffic for that address would still be handed to a tunnel
  # that has nowhere to send it.
  ip route show dev meshp0 | grep -q "100.90.${OCTET}.2" \
    && { ip route show dev meshp0 >&2; fail "the route to the revoked device survived"; }
  echo "  and its route withdrawn"

  # The relayed socket that served it is released. Nothing had ever exercised this before
  # revocation existed: a peer had no way to stop being relayed, so the retirement path in
  # relaylink ran only in its own tests.
  relayed_now="$(./bin/meshp status --socket "$SOCKET" \
    | sed -n 's|.*peers     \([0-9]*\) relayed.*|\1|p')"
  if [ -n "$relayed_now" ] && [ "$relayed_now" != "0" ]; then
    ./bin/meshp status --socket "$SOCKET" >&2
    fail "the revoked peer's relay socket was not released (${relayed_now} still served)"
  fi
  echo "  its relay socket was released"

  # The revoked device cannot come back.
  #
  # Asserted by restarting its daemon rather than by poking the challenge endpoint. That
  # endpoint deliberately does not check whether a membership exists — doing so would make
  # it an enumeration oracle for membership ids — so it answers a revoked device just as it
  # answers a made-up one. The signature check at connect time is what decides, and this is
  # the only place to observe it.
  ./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR2" --socket "$SOCKET2" \
    --log-level debug >>"$WORK/meshpd2.log" 2>&1 &
  AGENT2_PID=$!
  for _ in $(seq 1 20); do
    [ -S "$SOCKET2" ] && ./bin/meshp status --socket "$SOCKET2" >/dev/null 2>&1 && break
    sleep 1
  done

  # The agent is told only that authentication failed. That is deliberate — the reason a
  # membership is refused crosses a trust boundary towards a device that may no longer be
  # trusted — so this matches the refusal rather than the cause. The cause is in the
  # control plane's own log, asserted below, where an operator can see it.
  refused=0
  for _ in $(seq 1 20); do
    if grep -q "authentication failed" "$WORK/meshpd2.log"; then refused=1; break; fi
    sleep 1
  done
  if [ "$refused" != "1" ]; then
    echo "--- revoked agent log ---" >&2; tail -20 "$WORK/meshpd2.log" >&2
    fail "the revoked device was not refused a session"
  fi

  grep -qiE "revoked|membership is" "$CONTROL_LOG" \
    || { tail -20 "$CONTROL_LOG" >&2; fail "the control plane did not record why it refused"; }
  ./bin/meshp status --socket "$SOCKET2" | grep -qE 'session     connected' \
    && { ./bin/meshp status --socket "$SOCKET2" >&2; fail "a revoked device holds a session"; }
  echo "  and cannot open a new session"

  kill "$AGENT2_PID" 2>/dev/null || true
  wait "$AGENT2_PID" 2>/dev/null || true
  AGENT2_PID=""

  # The listen port survives a restart, which is what keeps the endpoints peers hold valid
  # and any NAT mapping alive.
  #
  # The interface is deleted before restarting on purpose. It outlives the daemon by design
  # (Invariant 15: a control-plane outage does not interrupt established networking), so a
  # restart on its own would find the port already correct and prove nothing about whether
  # anything was remembered.
  port_before="$(./bin/meshp status --socket "$SOCKET" | sed -n 's|.*listening   udp/\([0-9]*\).*|\1|p')"
  [ -n "$port_before" ] || { ./bin/meshp status --socket "$SOCKET" >&2; fail "status does not report a listen port"; }
  echo "  listening on udp/${port_before}"

  grep -q "\"listen_port\": *${port_before}" "$STATE_DIR/state.json" \
    || { fail "the listen port was not written to local state"; }

  kill "$AGENT_PID" 2>/dev/null || true
  wait "$AGENT_PID" 2>/dev/null || true
  ip link del meshp0
  ./bin/meshpd --reconcile-interval 2s --state-dir "$STATE_DIR" --socket "$SOCKET" \
    --log-level debug >>"$AGENT_LOG" 2>&1 &
  AGENT_PID=$!

  back=0
  for _ in $(seq 1 25); do
    if [ -S "$SOCKET" ] && ./bin/meshp status --socket "$SOCKET" 2>/dev/null | grep -qE 'interface   meshp0 \(up'; then
      back=1; break
    fi
    sleep 1
  done
  [ "$back" = "1" ] || { tail -20 "$AGENT_LOG" >&2; fail "the interface did not come back after a restart"; }

  port_after="$(./bin/meshp status --socket "$SOCKET" | sed -n 's|.*listening   udp/\([0-9]*\).*|\1|p')"
  [ "$port_after" = "$port_before" ] \
    || fail "the listen port changed across a restart: ${port_before} then ${port_after}"
  echo "  the same port after a restart and a deleted interface"
fi

echo "the same token a second time"
if ./bin/meshp join "$TOKEN" --control-url "$BASE" --socket "$SOCKET" >"$WORK/replay.out" 2>&1; then
  fail "a replayed token was accepted"
fi
sed 's/^/  /' "$WORK/replay.out"
grep -q 'already been used' "$WORK/replay.out" || fail "the replay was refused for the wrong reason"

echo "the enrolment is in the audit trail"
events="$(psql "$DB_URL" -tAqc "SELECT count(*) FROM audit_events
  WHERE action = 'device.enrolled' AND network_id = '${NETWORK_ID}'")"
# Two: the device under test and the second one that produced the delta.
[ "$events" = "2" ] || fail "${events} device.enrolled events, want 2"

echo "the session is cleared when the agent goes away"
kill "$AGENT_PID" 2>/dev/null || true
wait "$AGENT_PID" 2>/dev/null || true
AGENT_PID=""
cleared=0
for _ in $(seq 1 20); do
  rows="$(psql "$DB_URL" -tAqc "SELECT count(*) FROM membership_state
    WHERE control_session_id IS NOT NULL AND network_id = '${NETWORK_ID}'")"
  if [ "$rows" = "0" ]; then cleared=1; break; fi
  sleep 1
done
[ "$cleared" = "1" ] || fail "a membership is still marked connected after the agent exited"

# Left behind, the next start would warn about a stale socket for no reason.
if [ -S "$SOCKET" ]; then fail "the daemon left its socket behind on exit"; fi

echo "no private key material reached the control plane"
if grep -qiE 'private[_ ]?key' "$CONTROL_LOG"; then fail "the control plane log mentions a private key"; fi
if grep -qF "$TOKEN" "$CONTROL_LOG"; then fail "the control plane logged the plaintext token"; fi

echo
echo "enrolment and the control channel work end to end; a replayed token is refused"
